[package]
name = "marcus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.6.0"
html-escape = "0.2.11"
glob = "0.3.0"
url = "2.3.1"
